# e2e test for nginx helper plugin

name: End-to-End Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches:
#       - develop
#       - master

#   pull_request:
#     branches:
#       - develop
#       - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Run-wpe2e-TestCase:
    # The type of runner that the job will run on
    name: Playwright Tests
    runs-on: ubuntu-latest
    env:
      TESRESULT_TOKEN: ${{ secrets.TESRESULT_TOKEN }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SHA: ${{ github.event.pull_request.head.sha }}
      COMMIT_SHA: ${{ github.sha }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      working-directory: ./tests/e2e-playwright

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Check node version
      - name: Current directory and listings
        run: |
          pwd
          ls -al
        # Install config site
      - name: Install and config site
        uses: docker://rtcamp/base-wo:v1.0.0
        env:
          NODE_VERSION: 16
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}

      - name: Archive HTML Report on failure
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: report
          path: ./tests/e2e-playwright/config

      - name: run PR status
        if: ${{ always() }}
        run: node ./tests/e2e-playwright/bin/pr-status.js
        working-directory: ${{env.working_directory}}

      - name: Cleanup
        if: ${{ always() }}
        uses: rtCamp/action-cleanup@master